### ISSUE TITLE
Build a Chrome Extension boilerplate using the latest Chrome Web Extension manifest

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-js#1]
Build a Chrome Extension boilerplate using the latest [manifest format](https://developer.chrome.com/docs/extensions/mv3/manifest/) of Chrome Web Extension manifest version 3, with a frontend using svelte+vite+typescript. Functionality will follow in later tickets.

Also include a README that explains how to run it and add it to your local chrome to test.

### Acceptance Criteria

- [ ] A PR with a boilerplate. A script should be injected into visited web pages, allowing communication between the service worker and the web page. The script should add `window.sphinx` object to the global scope of the webpage, that we can add methods to later.
- [ ] A README

**Comment by Evanfeenstra** [comment]
![logo-64](https://github.com/stakwork/sphinx-js/assets/7184040/3baae8a7-35ae-41f5-8b58-02bd4759d352)
![logo-128](https://github.com/stakwork/sphinx-js/assets/7184040/d9e9a1ca-e412-4405-9902-c4e7ee3d3139)

Here a 64 and 128 logo

**Comment by dylanbathurst** [comment]
I can set this one up.

**Comment by dylanbathurst** [comment]
@ecurrencyhodler and @Evanfeenstra Here is the PR for the initial boilerplate. Let me know if anything in the readme isn't clear or if you're not able to get it working on your machine. https://github.com/stakwork/sphinx-js/pull/2
