### ISSUE TITLE
Create initial screen for chrome extension

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-js#5]
When a user first clicks on the extension, they will have an empty state with 0 secondbrains and 0 L402's. We are also skipping log-in authentication for the initial phase and only enabling functionality.

The user will be prompted with this screen. 
![1](https://github.com/stakwork/sphinx-js/assets/32662508/b0bedef7-29a7-44b0-9bfb-e5501ba0ca8f)

You can find the high fidelity [figma file here](https://www.figma.com/file/YuEbi4x32Mm8ZQJdnrs4uc/Second-Brain-Final-Designs?type=design&node-id=3790%3A11296&mode=design&t=22uPx1WKaUPKcZ2Q-1). 

This window also closes if you click outside the Chrome Extension popup window.

### Acceptance Criteria

- [ ] Tested on Chrome
- [ ] Posted screenshot of screen in the PR

**Comment by PlebeiusGaragicus** [comment]
I'd love to take this one.

**Comment by dylanbathurst** [comment]
@ecurrencyhodler The PR is here https://github.com/stakwork/sphinx-js/pull/13 and is ready to merge. Some things we may want to consider for the future are styling libraries. I prefer and used tailwindcss for this extension as it allows really rapid development. I also used the svg icons from the figma file, but we may want to consider using an icon library like feather icons or others, but it's totally fine if we use the ones in figma as well.

**Comment by ecurrencyhodler** [comment]
Closed by #13
